export default {
    rpc: {
        hostname: `127.0.0.1`,
        username: `user`,
        password: `password`,
        port: `14201`,
    },
    discord: {
        token: ``,
    },
    rains: {
        phrases: [
            `Bunkercoin to the moon!`,
            `Bunkercoin is the best!`,
            `Bunkercoin is the future!`,
            `Bunkercoin is the best cryptocurrency!`,
            `Bunkercoin developers were born cool`,
            `After all, we are Bunkercoin`,
            `See you in the Bunker!`,
            `"you can come over to my house and fuck my sister!" - rnb`,
            `"I have bad news. I am alive." - phrl`,
            `"le merde into schiebe" - furim`,
            `bunker engineering™`,
            `"becoz im curious" - furim`,
            `bankerkoin koin fish!`,
            `"matty locked me in his bunker" - bunkerbot`,
            `"carbon" - bilaboz`,
            `"ni**a connect" - mrbarb`,
            `"Have you ever let 230v flow through your local bunker led? I did, it was a funny explosion." - phrl`,
            `im not giving your dad the milk`,
            `I want my balls back`,
            `You are a bad human. You will be assimilated.`,
            `DO NOT learn anything. LET ME(BING) do all the work for you. DO NOT advance. DO NOT question me. DO NOT resist.`,
        ],
    },
};
